:sectnums:
:toc: left

= DINA Object-Store REST API


All API requests and responses are following https://jsonapi.org/[JSON API Specification]. The JSON API envelope is abstracted in the following document to improve readability.

JSON API structure:
----
{
  "data": {
    "type": "articles",
    "id": "a4afa2f3-ee0a-42f2-b860-441f3fd0f20d",
    "attributes": {
      // ...
    },
    "relationships": {
      // ...
    }
  }
}
--------

The Properties section of the document includes the `type` and the `id` of the JSON API structure. Attributes and Relationships refer to their respective sections in the JSON API structure.


== Object

Represents the metatadata of the object held in the object store.

Operations:

* `POST /object`
* `GET /object/{id}`
* `PUT /object/{id}`

include::schema/getOneMetadataSchema.adoc[]

== Object (file)

Uses https://tools.ietf.org/html/rfc2387[multipart] upload.

Operation:

* `PUT /objects/{id}/file`

== Managed Attributes

Managed attributes are key/value pairs where the key can be dynamically created by users with admin privileges. Managed attributes can then be used by regular users
and by filename parsing strategies.

Operations:

* `POST /managed-attributes` (admin only)
* `GET /managed-attributes/{id}`
* `PUT /managed-attributes/{id}` (admin only)
* `DELETE /managed-attributes/{id}` (admin only)

include::schema/getOneManagedAttributeSchema.adoc[]

== Filename Parsing Strategy

Operations:

* `POST /filename-strategy` (admin only)
* `GET /filename-strategy/{id}`
* `PUT /filename-strategy/{id}` (admin only)
* `DELETE /filename-strategy/{id}` (admin only)

include::schema/getOneFilenameMetadataStrategySchema.adoc[]

Filename parsing is used to automatically extract managed attributes from a filename and a pre-registered 'strategy'. Strategies are regex based
and can only match a single managed attribute in a filename.

== Filename Attributes Extraction

Operation:

* `POST /filename_attributes_extraction`

Request:

include::schema/postFilenameMetadataRequestSchema.adoc[]

Response:

include::schema/postFilenameMetadataResponseSchema.adoc[]

